'use client';

import { useState } from 'react';
import Link from 'next/link';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { AlertCircle, Download, PenTool, FileText, Clock } from 'lucide-react';
import { JurisdictionBadge } from '@/components/shared/JurisdictionBadge';
import { TrackBadge } from '@/components/shared/TrackBadge';
import { DOC_TYPE_META } from '@/lib/schemas/questions';
import { formatDate } from '@/lib/utils';
import type { Document, DocType } from '@/types/document';
import { useDocumentExport } from '@/stores/useDocumentExport';

interface DocumentViewerProps {
  document: Document;
}

export function DocumentViewer({ document }: DocumentViewerProps) {
  const { download, isLoading: isExporting } = useDocumentExport();
  const [downloadError, setDownloadError] = useState<string | null>(null);

  const handleDownload = async () => {
    setDownloadError(null);
    try {
      await download(document.id, document.title);
    } catch (err) {
      setDownloadError(err instanceof Error ? err.message : 'Failed to download PDF');
    }
  };

  const meta = DOC_TYPE_META[document.docType as DocType];
  const statusColor = {
    draft: 'bg-gray-100 text-gray-800',
    generated: 'bg-brand-blue/10 text-brand-blue',
    signed: 'bg-brand-green/10 text-brand-green',
  }[document.status];

  return (
    <div className="flex gap-6 max-w-7xl mx-auto">
      {/* Main content */}
      <div className="flex-1 min-w-0">
        <div className="mb-8">
          <Alert className="bg-brand-yellow/10 border-brand-yellow/20 mb-6">
            <AlertCircle className="h-4 w-4 text-brand-yellow" />
            <AlertTitle>AI-Generated Document</AlertTitle>
            <AlertDescription className="text-sm">
              ⚠️ This document was generated by AI for informational purposes only. It does not constitute legal advice. 
              Review with a qualified legal professional before use. ClauseGuard is not a law firm.
            </AlertDescription>
          </Alert>
        </div>

        {document.content && (
          <div className="prose prose-sm max-w-none text-brand-dark">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {document.content}
            </ReactMarkdown>
          </div>
        )}

        {!document.content && (
          <div className="text-center py-12 text-gray-500">
            <FileText className="w-12 h-12 mx-auto mb-4 opacity-50" />
            <p>No content available</p>
          </div>
        )}
      </div>

      {/* Sticky sidebar */}
      <div className="w-80 flex-shrink-0">
        <div className="sticky top-6 rounded-lg border border-gray-200 p-6 bg-white shadow-sm">
          {/* Metadata */}
          <div className="mb-6 space-y-3">
            <div className="flex gap-2 flex-wrap">
              <JurisdictionBadge jurisdiction={document.jurisdiction} />
              <TrackBadge track={document.track} />
            </div>

            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wide">Document Type</p>
              <p className="text-sm font-medium text-brand-dark">{meta?.label || document.docType}</p>
            </div>

            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wide">Status</p>
              <Badge className={`mt-1 ${statusColor}`}>
                {document.status === 'signed' ? '✓ Signed' : document.status === 'generated' ? 'Generated' : 'Draft'}
              </Badge>
            </div>

            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wide flex items-center gap-1">
                <Clock className="w-3 h-3" /> Created
              </p>
              <p className="text-sm text-brand-dark">{formatDate(document.createdAt)}</p>
            </div>

            {document.signedAt && (
              <div>
                <p className="text-xs text-gray-500 uppercase tracking-wide">Signed</p>
                <p className="text-sm text-brand-dark">{formatDate(document.signedAt)}</p>
              </div>
            )}
          </div>

          <div className="border-t border-gray-200 pt-6 space-y-3">
            {/* Download PDF */}
            <Button
              onClick={handleDownload}
              disabled={isExporting}
              className="w-full bg-brand-blue hover:bg-brand-blue/90 text-white"
            >
              <Download className="w-4 h-4 mr-2" />
              {isExporting ? 'Generating PDF...' : 'Download PDF'}
            </Button>

            {/* Sign Document */}
            <Link
              href={`/documents/${document.id}/sign`}
              className="block"
            >
              <Button
                variant="outline"
                className="w-full"
                disabled={document.status === 'signed'}
              >
                <PenTool className="w-4 h-4 mr-2" />
                {document.status === 'signed' ? 'Already Signed' : 'Sign Document'}
              </Button>
            </Link>

            {downloadError && (
              <div className="mt-4 p-3 bg-red-50 border border-red-200 rounded text-sm text-red-700">
                {downloadError}
              </div>
            )}

            {document.signature && document.status === 'signed' && (
              <div className="mt-4 p-4 bg-brand-green/5 rounded border border-brand-green/20">
                <p className="text-xs text-gray-600 mb-2">Signature Preview:</p>
                <img 
                  src={document.signature} 
                  alt="Signature" 
                  className="h-16 border border-gray-200 rounded bg-white"
                />
              </div>
            )}
          </div>

          <Link href="/dashboard" className="block mt-6">
            <Button variant="ghost" className="w-full">
              ← Back to Dashboard
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
}
