import type { Question, DocType } from '@/types/document';

export interface DocTypeMeta {
  label: string;
  description: string;
  estimatedMinutes: number;
}

export const DOC_TYPE_META: Record<DocType, DocTypeMeta> = {
  'service-agreement': { label: 'Service Agreement', description: 'Contract for freelance services with a client', estimatedMinutes: 1 },
  'client-nda': { label: 'Client NDA', description: 'Mutual non-disclosure agreement', estimatedMinutes: 1 },
  'payment-terms': { label: 'Payment Terms', description: 'Invoice and payment schedule', estimatedMinutes: 1 },
  'dispute-letter': { label: 'Dispute Letter', description: 'Formal demand letter for non-payment', estimatedMinutes: 1 },
  'ip-ownership': { label: 'IP Ownership', description: 'Intellectual property clause', estimatedMinutes: 1 },
  'cross-border-contract': { label: 'Cross-Border Contract', description: 'International service agreement', estimatedMinutes: 2 },
  'shareholder-agreement': { label: 'Shareholder Agreement', description: 'Equity and decision-making for co-founders', estimatedMinutes: 2 },
  'founder-vesting': { label: 'Founder Vesting', description: 'Vesting schedule for equity', estimatedMinutes: 2 },
  'employment-contract': { label: 'Employment Contract', description: 'Staff contract with all legal clauses', estimatedMinutes: 2 },
  'vendor-agreement': { label: 'Vendor Agreement', description: 'SLA with service providers', estimatedMinutes: 2 },
  'privacy-policy': { label: 'Privacy Policy', description: 'Data protection compliance document', estimatedMinutes: 2 },
  'investment-term-sheet': { label: 'Investment Term Sheet', description: 'Funding terms for investors', estimatedMinutes: 2 },
  'brand-deal-contract': { label: 'Brand Deal Contract', description: 'Influencer brand partnership agreement', estimatedMinutes: 2 },
  'exclusivity-clause': { label: 'Exclusivity Clause', description: 'Exclusivity terms for creators', estimatedMinutes: 1 },
  'content-license': { label: 'Content License', description: 'License existing content to brands', estimatedMinutes: 2 },
  'ugc-usage-rights': { label: 'UGC Usage Rights', description: 'User-generated content rights', estimatedMinutes: 1 },
  'talent-split-agreement': { label: 'Talent Split', description: 'Revenue split with manager/partner', estimatedMinutes: 2 },
  'collaboration-agreement': { label: 'Collaboration Agreement', description: 'Joint content project contract', estimatedMinutes: 2 },
};

export const QUESTION_SCHEMAS: Record<DocType, Question[]> = {
  'service-agreement': [
    { id: 'provider_name', label: 'Your full name or business name', type: 'text', required: true, placeholder: 'e.g., John Doe or Doe Design Studio' },
    { id: 'client_name', label: 'Client name / company', type: 'text', required: true, placeholder: 'e.g., Acme Corporation' },
    { id: 'client_address', label: 'Client address', type: 'text', required: false, placeholder: 'Full address' },
    { id: 'services_description', label: 'Description of services', type: 'textarea', required: true, placeholder: 'What work will you deliver?' },
    { id: 'total_fee', label: 'Total fee amount', type: 'number', required: true, placeholder: 'e.g., 50000' },
    { id: 'currency', label: 'Currency', type: 'select', required: true, options: ['NGN', 'KES', 'GHS', 'ZAR', 'USD', 'EUR', 'GBP'] },
    { id: 'payment_schedule', label: 'Payment schedule', type: 'select', required: true, options: ['50% upfront, 50% on completion', '100% upfront', 'Monthly installments', 'Upon completion', 'Net 30 days'] },
    { id: 'start_date', label: 'Project start date', type: 'date', required: true },
    { id: 'end_date', label: 'Expected end date', type: 'date', required: false },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'client-nda': [
    { id: 'disclosing_party', label: 'Your name / company', type: 'text', required: true },
    { id: 'receiving_party', label: 'Receiving party name', type: 'text', required: true },
    { id: 'receiving_address', label: 'Receiving party address', type: 'text', required: false },
    { id: 'purpose', label: 'Purpose of sharing', type: 'textarea', required: true, placeholder: 'Why are you sharing confidential information?' },
    { id: 'duration', label: 'Duration (years)', type: 'select', required: true, options: ['1', '2', '3', '5', 'Unlimited'] },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'payment-terms': [
    { id: 'business_name', label: 'Your business name', type: 'text', required: true },
    { id: 'client_name', label: 'Client name', type: 'text', required: true },
    { id: 'invoice_number', label: 'Invoice number', type: 'text', required: true, placeholder: 'e.g., INV-001' },
    { id: 'amount', label: 'Amount due', type: 'number', required: true },
    { id: 'currency', label: 'Currency', type: 'select', required: true, options: ['NGN', 'KES', 'GHS', 'ZAR', 'USD', 'EUR', 'GBP'] },
    { id: 'issue_date', label: 'Issue date', type: 'date', required: true },
    { id: 'due_date', label: 'Due date', type: 'date', required: true },
    { id: 'late_fee', label: 'Late fee percentage (optional)', type: 'number', required: false, placeholder: 'e.g., 5' },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'dispute-letter': [
    { id: 'your_name', label: 'Your full name', type: 'text', required: true },
    { id: 'your_address', label: 'Your address', type: 'text', required: true },
    { id: 'client_name', label: 'Client name / company', type: 'text', required: true },
    { id: 'client_address', label: 'Client address', type: 'text', required: true },
    { id: 'invoice_number', label: 'Invoice number', type: 'text', required: true },
    { id: 'amount', label: 'Amount outstanding', type: 'number', required: true },
    { id: 'currency', label: 'Currency', type: 'select', required: true, options: ['NGN', 'KES', 'GHS', 'ZAR', 'USD'] },
    { id: 'original_due_date', label: 'Original due date', type: 'date', required: true },
    { id: 'days_overdue', label: 'Days overdue', type: 'number', required: true },
    { id: 'final_deadline', label: 'Final payment deadline', type: 'date', required: true },
    { id: 'preferred_resolution', label: 'Preferred resolution', type: 'textarea', required: false, placeholder: 'e.g., Payment within 14 days' },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'ip-ownership': [
    { id: 'project_name', label: 'Project name', type: 'text', required: true },
    { id: 'creator_name', label: 'Creator name', type: 'text', required: true },
    { id: 'client_name', label: 'Client name', type: 'text', required: true },
    { id: 'ip_type', label: 'Type of IP', type: 'select', required: true, options: ['Software', 'Design', 'Content', 'Brand Assets', 'Other'] },
    { id: 'ownership_trigger', label: 'When does ownership transfer?', type: 'select', required: true, options: ['Upon full payment', 'Immediately', 'After 30 days', 'Never - perpetual license'] },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'cross-border-contract': [
    { id: 'provider_name', label: 'Your name / company', type: 'text', required: true },
    { id: 'provider_country', label: 'Your country', type: 'select', required: true, options: ['Nigeria', 'Kenya', 'Ghana', 'South Africa', 'Other'] },
    { id: 'client_name', label: 'Client name / company', type: 'text', required: true },
    { id: 'client_country', label: 'Client country', type: 'text', required: true },
    { id: 'services_description', label: 'Description of services', type: 'textarea', required: true },
    { id: 'total_fee', label: 'Total fee', type: 'number', required: true },
    { id: 'currency', label: 'Currency', type: 'select', required: true, options: ['USD', 'EUR', 'GBP', 'NGN', 'KES', 'GHS', 'ZAR'] },
    { id: 'payment_method', label: 'Payment method', type: 'select', required: true, options: ['Bank transfer', 'PayPal', 'Western Union', 'Crypto', 'Other'] },
    { id: 'start_date', label: 'Start date', type: 'date', required: true },
    { id: 'end_date', label: 'End date', type: 'date', required: false },
    { id: 'dispute_resolution', label: 'Dispute resolution', type: 'select', required: true, options: ['Arbitration', 'Court in provider country', 'Court in client country', 'Mediation'] },
    { id: 'jurisdiction', label: 'Governing jurisdiction (primary)', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'shareholder-agreement': [
    { id: 'company_name', label: 'Company name', type: 'text', required: true },
    { id: 'registration_number', label: 'Company registration number', type: 'text', required: false },
    { id: 'jurisdiction', label: 'Jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
    { id: 'shareholder1_name', label: 'Shareholder 1 name', type: 'text', required: true },
    { id: 'shareholder1_role', label: 'Shareholder 1 role', type: 'select', required: true, options: ['Founder', 'Investor', 'Employee', 'Advisor', 'Other'] },
    { id: 'shareholder1_equity', label: 'Shareholder 1 equity %', type: 'number', required: true },
    { id: 'shareholder2_name', label: 'Shareholder 2 name', type: 'text', required: true },
    { id: 'shareholder2_role', label: 'Shareholder 2 role', type: 'select', required: true, options: ['Founder', 'Investor', 'Employee', 'Advisor', 'Other'] },
    { id: 'shareholder2_equity', label: 'Shareholder 2 equity %', type: 'number', required: true },
    { id: 'shareholder3_name', label: 'Shareholder 3 name', type: 'text', required: false },
    { id: 'shareholder3_equity', label: 'Shareholder 3 equity %', type: 'number', required: false },
    { id: 'shareholder4_name', label: 'Shareholder 4 name', type: 'text', required: false },
    { id: 'shareholder4_equity', label: 'Shareholder 4 equity %', type: 'number', required: false },
    { id: 'shareholder5_name', label: 'Shareholder 5 name', type: 'text', required: false },
    { id: 'shareholder5_equity', label: 'Shareholder 5 equity %', type: 'number', required: false },
    { id: 'decision_threshold', label: 'Major decision threshold', type: 'select', required: true, options: ['50%', '66%', '75%', 'Unanimous'] },
    { id: 'drag_along', label: 'Drag-along rights', type: 'select', required: true, options: ['Yes', 'No'] },
    { id: 'tag_along', label: 'Tag-along rights', type: 'select', required: true, options: ['Yes', 'No'] },
    { id: 'refusal_right', label: 'Right of first refusal', type: 'select', required: true, options: ['Yes', 'No'] },
  ],
  'founder-vesting': [
    { id: 'company_name', label: 'Company name', type: 'text', required: true },
    { id: 'founder_name', label: 'Founder name', type: 'text', required: true },
    { id: 'equity_amount', label: 'Equity amount (%)', type: 'number', required: true, placeholder: 'e.g., 10' },
    { id: 'vesting_period', label: 'Vesting period (years)', type: 'select', required: true, options: ['1', '2', '3', '4', '5'] },
    { id: 'cliff_period', label: 'Cliff period (months)', type: 'select', required: true, options: ['6', '12', '18', '24'] },
    { id: 'vesting_frequency', label: 'Vesting frequency', type: 'select', required: true, options: ['Monthly', 'Quarterly', 'Annually'] },
    { id: 'acceleration', label: 'Acceleration on acquisition', type: 'select', required: true, options: ['Single trigger', 'Double trigger', 'None'] },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'employment-contract': [
    { id: 'employer_name', label: 'Employer name', type: 'text', required: true },
    { id: 'employer_address', label: 'Employer address', type: 'text', required: true },
    { id: 'employee_name', label: 'Employee name', type: 'text', required: true },
    { id: 'employee_address', label: 'Employee address', type: 'text', required: true },
    { id: 'job_title', label: 'Job title', type: 'text', required: true },
    { id: 'employment_type', label: 'Employment type', type: 'select', required: true, options: ['Full-time', 'Part-time', 'Contract', 'Intern'] },
    { id: 'start_date', label: 'Start date', type: 'date', required: true },
    { id: 'salary', label: 'Salary amount', type: 'number', required: true },
    { id: 'salary_currency', label: 'Currency', type: 'select', required: true, options: ['NGN', 'KES', 'GHS', 'ZAR'] },
    { id: 'salary_frequency', label: 'Payment frequency', type: 'select', required: true, options: ['Monthly', 'Bi-weekly', 'Weekly'] },
    { id: 'probation_period', label: 'Probation period (months)', type: 'select', required: true, options: ['0', '1', '2', '3', '6'] },
    { id: 'notice_period', label: 'Notice period (weeks)', type: 'select', required: true, options: ['1', '2', '4', '8'] },
    { id: 'working_hours', label: 'Working hours per week', type: 'number', required: true, placeholder: 'e.g., 40' },
    { id: 'work_location', label: 'Work location', type: 'select', required: true, options: ['On-site', 'Remote', 'Hybrid'] },
    { id: 'non_compete', label: 'Non-compete clause', type: 'select', required: true, options: ['Yes', 'No'] },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'vendor-agreement': [
    { id: 'company_name', label: 'Your company name', type: 'text', required: true },
    { id: 'vendor_name', label: 'Vendor name', type: 'text', required: true },
    { id: 'vendor_address', label: 'Vendor address', type: 'text', required: true },
    { id: 'service_description', label: 'Service description', type: 'textarea', required: true },
    { id: 'service_start', label: 'Service start date', type: 'date', required: true },
    { id: 'service_end', label: 'Service end date', type: 'date', required: false },
    { id: 'fee', label: 'Service fee', type: 'number', required: true },
    { id: 'currency', label: 'Currency', type: 'select', required: true, options: ['NGN', 'KES', 'GHS', 'ZAR', 'USD', 'EUR'] },
    { id: 'payment_terms', label: 'Payment terms', type: 'select', required: true, options: ['Net 15', 'Net 30', 'Net 45', 'Upon completion'] },
    { id: 'sla', label: 'SLA requirements', type: 'textarea', required: false },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'privacy-policy': [
    { id: 'company_name', label: 'Company / product name', type: 'text', required: true },
    { id: 'website_url', label: 'Website URL', type: 'text', required: true, placeholder: 'https://...' },
    { id: 'contact_email', label: 'Contact email', type: 'text', required: true },
    { id: 'data_types', label: 'Data types collected', type: 'checkbox-group', required: true, options: ['Name', 'Email', 'Phone', 'Address', 'Payment info', 'Device data', 'Cookies', 'Location', 'Other'] },
    { id: 'data_purpose', label: 'Purpose of data collection', type: 'textarea', required: true },
    { id: 'third_party_sharing', label: 'Third-party sharing', type: 'select', required: true, options: ['Yes', 'No'] },
    { id: 'third_party_details', label: 'Third parties (if any)', type: 'textarea', required: false },
    { id: 'retention_period', label: 'Data retention period', type: 'select', required: true, options: ['6 months', '1 year', '2 years', 'Until consent withdrawn', 'Indefinite'] },
    { id: 'user_rights', label: 'User rights offered', type: 'checkbox-group', required: true, options: ['Access', 'Rectification', 'Deletion', 'Portability', 'Opt-out'] },
    { id: 'jurisdiction', label: 'Jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'investment-term-sheet': [
    { id: 'company_name', label: 'Company name', type: 'text', required: true },
    { id: 'company_reg', label: 'Company registration', type: 'text', required: false },
    { id: 'investor_name', label: 'Investor name', type: 'text', required: true },
    { id: 'investment_amount', label: 'Investment amount', type: 'number', required: true },
    { id: 'currency', label: 'Currency', type: 'select', required: true, options: ['USD', 'EUR', 'GBP', 'NGN', 'KES', 'GHS', 'ZAR'] },
    { id: 'valuation', label: 'Pre-money valuation', type: 'number', required: true },
    { id: 'equity_offered', label: 'Equity offered %', type: 'number', required: true },
    { id: 'instrument', label: 'Investment instrument', type: 'select', required: true, options: ['SAFE', 'Convertible Note', 'Equity'] },
    { id: 'board_seats', label: 'Investor board seats', type: 'number', required: true },
    { id: 'liquidation_pref', label: 'Liquidation preference', type: 'select', required: true, options: ['1x', '1.5x', '2x', 'None'] },
    { id: 'anti_dilution', label: 'Anti-dilution protection', type: 'select', required: true, options: ['Full ratchet', 'Weighted average', 'None'] },
    { id: 'vesting_founder', label: 'Founder vesting', type: 'select', required: true, options: ['Yes', 'No'] },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'brand-deal-contract': [
    { id: 'creator_name', label: 'Creator name / handle', type: 'text', required: true },
    { id: 'creator_legal_name', label: 'Creator legal name', type: 'text', required: false },
    { id: 'brand_name', label: 'Brand name', type: 'text', required: true },
    { id: 'brand_contact', label: 'Brand contact person', type: 'text', required: true },
    { id: 'campaign_product', label: 'Campaign / product', type: 'text', required: true },
    { id: 'deliverables', label: 'Deliverables', type: 'textarea', required: true, placeholder: 'List all content to be delivered' },
    { id: 'platforms', label: 'Platforms', type: 'checkbox-group', required: true, options: ['Instagram', 'TikTok', 'YouTube', 'Twitter/X', 'LinkedIn', 'Facebook'] },
    { id: 'campaign_start', label: 'Campaign start date', type: 'date', required: true },
    { id: 'campaign_end', label: 'Campaign end date', type: 'date', required: true },
    { id: 'fee', label: 'Total fee', type: 'number', required: true },
    { id: 'currency', label: 'Currency', type: 'select', required: true, options: ['NGN', 'KES', 'GHS', 'ZAR', 'USD', 'EUR', 'GBP'] },
    { id: 'payment_terms', label: 'Payment terms', type: 'select', required: true, options: ['Before delivery', '50/50', 'Net 30', 'Upon completion'] },
    { id: 'exclusivity', label: 'Exclusivity required', type: 'select', required: true, options: ['Yes', 'No'] },
    { id: 'exclusivity_category', label: 'Exclusivity category', type: 'text', required: false, placeholder: 'e.g., Skincare, Finance' },
    { id: 'exclusivity_duration', label: 'Exclusivity duration (months)', type: 'number', required: false },
    { id: 'content_approval', label: 'Content approval required', type: 'select', required: true, options: ['Yes', 'No'] },
    { id: 'usage_rights', label: 'Usage rights granted to brand', type: 'select', required: true, options: ['Yes', 'No'] },
    { id: 'usage_platforms', label: 'Usage platforms (if yes)', type: 'checkbox-group', required: false, options: ['Organic only', 'Paid ads', 'Website', 'Email'] },
    { id: 'usage_duration', label: 'Usage duration (months)', type: 'number', required: false },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'exclusivity-clause': [
    { id: 'creator_name', label: 'Creator name', type: 'text', required: true },
    { id: 'brand_name', label: 'Brand name', type: 'text', required: true },
    { id: 'exclusivity_type', label: 'Exclusivity type', type: 'select', required: true, options: ['Platform', 'Product category', 'Territory'] },
    { id: 'scope_details', label: 'Scope details', type: 'textarea', required: true, placeholder: 'Describe the exclusivity scope' },
    { id: 'duration', label: 'Duration (months)', type: 'number', required: true },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'content-license': [
    { id: 'licensor_name', label: 'Licensor (you)', type: 'text', required: true },
    { id: 'licensee_name', label: 'Licensee (brand)', type: 'text', required: true },
    { id: 'content_description', label: 'Content description', type: 'textarea', required: true, placeholder: 'Describe the content being licensed' },
    { id: 'license_type', label: 'License type', type: 'select', required: true, options: ['Exclusive', 'Non-exclusive'] },
    { id: 'platforms', label: 'Permitted platforms', type: 'checkbox-group', required: true, options: ['Instagram', 'TikTok', 'YouTube', 'Website', 'TV', 'Print'] },
    { id: 'territory', label: 'Territory', type: 'select', required: true, options: ['Worldwide', 'Africa', 'Specific country'] },
    { id: 'territory_details', label: 'Territory details', type: 'text', required: false },
    { id: 'duration', label: 'Duration (months)', type: 'number', required: true },
    { id: 'permitted_uses', label: 'Permitted uses', type: 'textarea', required: true },
    { id: 'fee', label: 'License fee', type: 'number', required: true },
    { id: 'currency', label: 'Currency', type: 'select', required: true, options: ['NGN', 'KES', 'GHS', 'ZAR', 'USD', 'EUR'] },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'ugc-usage-rights': [
    { id: 'brand_name', label: 'Brand name', type: 'text', required: true },
    { id: 'creator_name', label: 'Creator name', type: 'text', required: true },
    { id: 'content_description', label: 'Content description', type: 'textarea', required: true },
    { id: 'usage_type', label: 'Usage type', type: 'checkbox-group', required: true, options: ['Social media', 'Paid ads', 'Website', 'Email marketing', 'Print'] },
    { id: 'duration', label: 'Duration (months)', type: 'number', required: true },
    { id: 'territory', label: 'Territory', type: 'select', required: true, options: ['Worldwide', 'Africa', 'Specific country'] },
    { id: 'compensation', label: 'Compensation', type: 'number', required: true },
    { id: 'currency', label: 'Currency', type: 'select', required: true, options: ['NGN', 'KES', 'GHS', 'ZAR', 'USD', 'EUR'] },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'talent-split-agreement': [
    { id: 'talent_name', label: 'Talent name', type: 'text', required: true },
    { id: 'manager_name', label: 'Manager / partner name', type: 'text', required: true },
    { id: 'split_percentage', label: 'Talent share %', type: 'number', required: true },
    { id: 'manager_percentage', label: 'Manager share %', type: 'number', required: true },
    { id: 'revenue_sources', label: 'Revenue sources', type: 'checkbox-group', required: true, options: ['Brand deals', 'Merchandise', 'Tips/donations', 'Platform revenue', 'Other'] },
    { id: 'payment_schedule', label: 'Payment schedule', type: 'select', required: true, options: ['Weekly', 'Bi-weekly', 'Monthly'] },
    { id: 'expense_split', label: 'Expense sharing', type: 'textarea', required: false },
    { id: 'term_start', label: 'Start date', type: 'date', required: true },
    { id: 'term_end', label: 'End date', type: 'date', required: false },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
  'collaboration-agreement': [
    { id: 'creator1_name', label: 'Creator 1 name', type: 'text', required: true },
    { id: 'creator2_name', label: 'Creator 2 name', type: 'text', required: true },
    { id: 'creator3_name', label: 'Creator 3 name', type: 'text', required: false },
    { id: 'creator4_name', label: 'Creator 4 name', type: 'text', required: false },
    { id: 'project_description', label: 'Project description', type: 'textarea', required: true },
    { id: 'content_type', label: 'Content type', type: 'select', required: true, options: ['Video', 'Post series', 'Livestream', 'Podcast', 'Blog', 'Other'] },
    { id: 'platforms', label: 'Platforms', type: 'checkbox-group', required: true, options: ['Instagram', 'TikTok', 'YouTube', 'Twitter/X', 'Other'] },
    { id: 'creator1_share', label: 'Creator 1 revenue share %', type: 'number', required: true },
    { id: 'creator2_share', label: 'Creator 2 revenue share %', type: 'number', required: true },
    { id: 'creator3_share', label: 'Creator 3 revenue share %', type: 'number', required: false },
    { id: 'creator4_share', label: 'Creator 4 revenue share %', type: 'number', required: false },
    { id: 'revenue_sources', label: 'Revenue sources', type: 'checkbox-group', required: true, options: ['Brand deals', 'Platform monetization', 'Merchandise', 'Tips', 'Other'] },
    { id: 'credit_attribution', label: 'Credit / attribution', type: 'textarea', required: true },
    { id: 'content_ownership', label: 'Content ownership', type: 'select', required: true, options: ['Joint', 'Equal split', 'By contribution'] },
    { id: 'decision_making', label: 'Decision-making process', type: 'select', required: true, options: ['Unanimous', 'Majority', 'Lead creator decides'] },
    { id: 'exit_clause', label: 'Exit clause', type: 'textarea', required: false },
    { id: 'jurisdiction', label: 'Governing jurisdiction', type: 'select', required: true, options: ['NG', 'KE', 'GH', 'ZA'] },
  ],
};